function controlVal = laser_mW_to_control(obj,mW)
    % Convert a desired value in mW to a control voltage for the laser
    %
    % function controlVal = zapit.pointer.laser_mW_to_control(mW)
    %
    % Purpose
    % The user will request a laser power in mW at the sample. If a calibration curve has
    % been generated by zapit.pointer.generateLaserCalibrationCurve, this method anchors it
    % to the measured min/max power and linearly interpolates it to convert the requested
    % mW value to the equivalent control voltage. If there is no laser fit, a linear
    % estimate is made. This will be very accurate if you have gone through the steps
    % described in the user guide.
    %
    %
    % Inputs
    % mW - requested value in mW
    %
    % Outputs
    % controlVal - the control voltage that will produce the requested mW value.
    %
    %
    % Rob Campbell - SWC 2022
    %
    % See also:
    % zapit.pointer.setLaserInMW
    % zapit.pointer.generateLaserCalibrationCurve
    % zapit.utils.fitLaserPowerCurve



    % Make local copies of setting needed in multiple places below
    minPower = obj.settings.laser.laserMinMax_mW(1);
    maxPower = obj.settings.laser.laserMinMax_mW(2);
    maxCV = obj.settings.laser.laserMinMaxControlVolts(2);

    if isempty(obj.laserFit)
        % The laser fit is only needed if the laser is not linear. Since so far only very cheap
        % lasers have been found to be non-linear we can not make a fuss if the fit is missing and
        % just assume it is linear.

        controlVal = (mW/maxPower) * maxCV - minPower ;
    else
        % The user has a measured calibration curve. The photodiode is uncalibrated, so the
        % fitted (denoised) sensor values are in arbitrary units. We anchor them to real mW
        % using the min and max power measured with a power meter (laserMinMax_mW). This
        % gives a lookup table of mW against control voltage, which we invert by linear
        % interpolation. The fit itself was already made in zapit.utils.fitLaserPowerCurve,
        % so we do not repeat it here.
        controlV = obj.laserFit.controlValues;

        fittedSensor = obj.laserFit.fittedSensorValues;

        % Anchor the normalised curve to the measured mW range
        mWvals = minPower + (fittedSensor - min(fittedSensor)) / ...
                    (max(fittedSensor) - min(fittedSensor)) * (maxPower - minPower);

        % Interpolate to find the control voltage at the requested power
        controlVal = interp1(mWvals, controlV, mW);
    end

    % Make sure the control value is not out of bounds. A request above the calibrated
    % maximum gives controlVal>maxCV (linear branch) or NaN (interpolated branch); either
    % way we cap it and warn. A request below the calibrated minimum (NaN from the
    % interpolated branch) is set to the minimum control voltage.
    if (~isnan(controlVal) && controlVal>maxCV) || (isnan(controlVal) && mW>maxPower)
        fprintf(['\n ** Requested value of %0.2f mW is out of range. ', ...
            'Capping at laser max power of %0.2f mW\n\n'],...
            mW, maxPower)
        controlVal = maxCV;
    elseif isnan(controlVal)
        controlVal = obj.settings.laser.laserMinMaxControlVolts(1);
    end


end % laser_mW_to_control
